version: '3.6'

services:
    image_server:
        container_name: image_service 
        hostname: image_service 
        image: rencinrig/image.service:1.0.0-SNAPSHOT
        restart: always
        environment:
        - EXO_IMAGE_HOME=/code/
        ports:
        - "8222:8222"
        # point to user specific keys below
        volumes:
        - "./logs:/code/logs"
        - "./config/application.properties:/code/config/application.properties"
        - "./config/log4j.properties:/code/config/log4j.properties"
